Support building with libelogind as an alternative libsystemd provider
rfjakob/systembus-notify pull request #10
Opened 2022-09-26 14:35 UTC by aidanharris

This uses pkg-config to fetch the include dir and ldflags instead of hardcoding it.

Tested on my Gentoo system with elogind and compile-tested on an Archlinux system.

2022-10-15 10:56 UTC, rfjakob requested changes
Hi, thanks for the patch!

One problem I see: If a user has neither libsystemd nor libelogind installed, they will get an error about libelogind missing.

I think if neither is installed the error message should tell the user to install libsystemd.

2022-10-15 11:03 UTC, rfjakob commented
Yeah, just tested in Debian docker container with neither libsystemd-dev nor libelogind installed:

```
# make
Package libelogind was not found in the pkg-config search path.
Perhaps you should add the directory containing `libelogind.pc'
to the PKG_CONFIG_PATH environment variable

No package 'libelogind' found
Package libelogind was not found in the pkg-config search path.
Perhaps you should add the directory containing `libelogind.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libelogind' found

cc  -Wall -Wextra -Wformat-security -Wconversion -fstack-protector-all -std=gnu99 -g  -I/usr/include/systemd -o systembus-notify *.c 
main.c:4:10: fatal error: sd-bus.h: No such file or directory
    4 | #include <sd-bus.h>
      |          ^~~~~~~~~~
compilation terminated.
notify.c:4:10: fatal error: sd-bus.h: No such file or directory
    4 | #include <sd-bus.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:8: systembus-notify] Error 1
```

2022-10-15 11:14 UTC, aidanharris commented
> I think if neither is installed the error message should tell the user to install libsystemd.

Fixed by inverting the condition. It's better to assume systemd is installed (systems using libelogind won't have libsystemd installed)

2022-10-15 20:07 UTC, rfjakob commented
Better, but, why replace `#include <systemd/sd-bus.h>` with `<sd-bus.h>`? Does libelogind not provide the systemd directory?

2022-10-15 20:11 UTC, rfjakob commented
Looking at https://github.com/elogind/elogind/blob/main/src/systemd/sd-bus.h , it seems that elogind *does* provide the systemd directory.

2022-10-15 21:01 UTC, aidanharris commented
> Does libelogind not provide the systemd directory?

It's installed at /usr/include/elogind, probably to not conflict with /usr/include/systemd if somebody were to install both libsystemd and libelogind at the same time, which I think is technically possible but there's no reason to do that.

Debian blocks that from happening so it should be okay to check if libelogind is installed first (it shouldn't be on most systems) and always use systemd in any other case.

```bash
# apt install -y libsystemd-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libelogind0 : Conflicts: libsystemd0
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

If for some strange reason somebody had both libsystemd and libelogind installed they could still force libsystemd to be used by running:

```bash
make LIBSYSTEMD_PROVIDER=libsystemd 
```

2022-10-15 21:13 UTC, aidanharris commented
> Looking at https://github.com/elogind/elogind/blob/main/src/systemd/sd-bus.h , it seems that elogind _does_ provide the systemd directory.

For some reason this didn't work the first time I tried this but it does now. I'm not sure why it didn't work on my first attempt. I'll push again without the changes to main.c and notify.c

2022-10-15 21:23 UTC, aidanharris commented
The second push was to remove the `-I/usr/include/systemd` but that doesn't show in Github's webui for some reason.

2022-10-21 11:29 UTC, closed without merging

2022-10-21 11:30 UTC, rfjakob commented
Hi, I implemented this a little differently, please see if

https://github.com/rfjakob/systembus-notify/commit/f5f7a4134b6801a7d970ff8133741a9a1e7ca792#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R3

works for you.